import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientInit from "./components/ClientInit/ClientInit";
import SupportWidget from "./components/SupportWidget/SupportWidget";


const inter = Inter({
  subsets: ["latin", "cyrillic"], // нужные сабсеты
  weight: ["400", "500", "600", "700"], // какие начертания
  variable: "--font-inter", // кастомное CSS-переменное имя
  display: "swap", // чтобы текст не мигал
});



export const metadata: Metadata = {
  title: "aCapital",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${inter.variable} ${inter.variable}`}>
        <ClientInit>
          {children}
          <SupportWidget />
        </ClientInit>
      </body>
    </html>
  );
}
